export default[
    {
      path:"/",
      name:"Layout",
      component:()=>import("../views/LayOut.vue"),
      redirect:"/index",
      children:[
        {
          path:"/index",
          name:"index",
          component:()=>import("../views/index/HomeIndex")
        },
        {
          path:"/orders/list",
          name:"orders_list",
          component:()=>import("../views/orders/OrdersList"),
          meta:{bread:["订单管理","订单列表"]}
        },
        {
          path:"/waybill/in",
          name:"waybill_in",
          component:()=>import("../views/waybill/WaybillIn"),
          
        },
        {
          path:"/waybill/list",
          name:"waybill_list",
          component:()=>import("../views/waybill/WaybillList"),
          meta:{bread:["运单管理","运单列表"],keepAlive:true}
        },
        {
          path:"/waybill/list/detail",
          name:"waybill_list_detail",
          component:()=>import("../views/waybill/WaybillDetail"),
          meta:{bread:["运单管理","运单列表","运单详情"]}
        },
        {
          path:"/depart/data",
          name:"waybill_list_in",
          meta:{bread:["发车管理","发车数据单"]},
          component:()=>import("../views/depart/DepartData.vue")
        }
      ]
    },
    {
      //加导航守卫，不能直接通过最上方修改路径就能访问到网页页面
      path:"/login",
      name:"Login",
      component:()=>import("../views/LogIn.vue")
    },
   
  ]